# -*- coding: utf-8 -*-
"""Stock Portfolio Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsJednPKXgW7lkYbAekg_xVJr0prbv_9
"""

stock_prices = {
    "AAPL": 180.50,
    "GOOGL": 2800.00,
    "MSFT": 350.00,
    "TSLA": 720.00,
    "AMZN": 135.50
}

portfolio = {
    "AAPL": 10,
    "GOOGL": 2,
    "MSFT": 5,
    "TSLA": 3,
    "AMZN": 4
}

total_investment = 0

print("📈 Stock Portfolio Summary\n")
print(f"{'Stock':<6} {'Shares':<6} {'Price':<10} {'Value':<10}")

for stock, shares in portfolio.items():
    price = stock_prices.get(stock, 0)
    value = shares * price
    total_investment += value
    print(f"{stock:<6} {shares:<6} ${price:<10.2f} ${value:<10.2f}")

print(f"\n💰 Total Investment: ${total_investment:.2f}")